[mypy]
ignore_missing_imports = False

# Per-module overrides to silence missing stub errors for these third-party libs
[mypy-caldav.*]
ignore_missing_imports = True

[mypy-edgy.*]
ignore_missing_imports = True

[mypy-ravyn.*]
ignore_missing_imports = True
